system {
    host-name cpe-3;
    root-authentication {
        encrypted-password "$6$MP36QtHz$xEtZKwj63cBNf/Qe0XDbmAZGJWAvJI.OZiutFL/aiNRsgyfHfMcIV9yndq1Qay2SD4Po4.cAeFfzH1Ytf2ExD1"; ## SECRET-DATA
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$NLGThWg/$OOFOfpEzvHzaJlYy.gIR4hVzlDikx1DXWazuNRXBnFoiiMjaprO.j7AnchYwHw9nlJr0FSz1FzQNSBNTCEYP3/"; ## SECRET-DATA
            }
        }
        user jsullivan {
            uid 2001;
            class super-user;
            authentication {
                encrypted-password "$6$ohJka5OO$sfgqjALCi5sfjMn6WDH8Zd2zygIDHg43lcPhTy3ZlP/Km7Fc2Z12bj6lmCkYqVD0hvrQhH5yO2QKXgE.kj63M."; ## SECRET-DATA
            }
        }
    }
    services {
        netconf {
            ssh;
        }
        ssh {
            root-login allow;
        }
    }
    management-instance;
}
chassis {
    fpc 0 {
        pic 0 {
            number-of-ports 12;
        }
    }
}
interfaces {
    ge-0/0/0 {
        description "To MX3";
        unit 0 {
            family inet {
                address 192.168.0.14/30;
            }
        }
    }
    ge-0/0/1 {
        description DEB3;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 10 {
            vlan-id 10;
            family inet {
                address 172.3.10.1/24;
            }
        }
        unit 20 {
            vlan-id 20;
            family inet {
                address 172.3.20.1/24;
            }
        }
        unit 30 {
            vlan-id 30;
            family inet {
                address 172.3.30.1/24;
            }
        }
        unit 40 {
            vlan-id 40;
            family inet {
                address 172.3.40.1/24;
            }
        }
        unit 50 {
            vlan-id 50;
            family inet {
                address 172.3.50.1/24;
            }
        }
        unit 60 {
            vlan-id 60;
            family inet {
                address 172.3.60.1/24;
            }
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 10.0.0.15/24;
            }
            family inet6 {
                address 2001:db8::2/64;
            }
        }
    }
}
policy-options {
    policy-statement DIRECT {
        term 1 {
            from {
                route-filter 172.3.0.0/16 longer;
            }
            then accept;
        }
        term 2 {
            then reject;
        }
    }
}
routing-instances {
    mgmt_junos {
        routing-options {
            rib mgmt_junos.inet6.0 {
                static {
                    route ::/0 next-hop 2001:db8::1;
                }
            }
            static {
                route 0.0.0.0/0 next-hop 10.0.0.2;
            }
        }
    }
}
routing-options {
    autonomous-system 65001;
}
protocols {
    bgp {
        group PE {
            type external;
            log-updown;
            export DIRECT;
            peer-as 999;
            neighbor 192.168.0.13;
        }
    }
}
